const busStops = [
    "Central Bus Stand",
    "Railway Station",
    "Rankala Lake",
    "New Palace",
    "Rajarampuri",
    "Kalamba",
    "Shivaji Peth",
    "Sambhaji Nagar",
    "Kasba Bawada",
    "Udyam Nagar",
    "Laxmipuri",
    "Jaysingpur",
    "Ichalkaranji",
    "Bindu Chowk",                   
    "Tarabai Park",
    "Market Yard",
    "Shahupuri",
    "Shivaji University",
    "Jaysingpur",
    "Ichalkaranji",
    "Mahadwar Road",
    "Bindu Chowk",
    "Shivaji Peth",
    "Laxmipuri",
    "Sambhaji Nagar",
    "Kasba Bawada",
    "Line Bazaar",
    "Udyam Nagar",
    "Kawala Naka"
];